sudo: required
services:
    - docker

before_install:
    - docker build -t cu/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t cu/multi-client ./client
    - docker build -t cu/multi-nginx ./nginx
    - docker build -t cu/multi-server ./server
    - docker build -t cu/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push cu/multi-client
    - docker push cu/multi-nginx
    - docker push cu/multi-server
    - docker push cu/multi-worker